{% extends '../../framework/templates/default/default.html.swig' %}
{% block content %}

  {% include '../../framework/design/decorations/triangle/x-triangle/x-triangle.html.swig' %}
  {% include '../../framework/design/decorations/saquo/x-saquo/x-saquo.html.swig' %}
  {% include '../../framework/design/decorations/arrow-with-triangle/x-arrow-with-triangle/x-arrow-with-triangle.html.swig' %}
  {% include '../../framework/design/decorations/arrow-with-saquo/x-arrow-with-saquo/x-arrow-with-saquo.html.swig' %}

{% endblock %}
