<nav class="menu">
  <h3 class="menu__title">Menu</h3>

  <ul class="menu__items">
    <li class="li">Item 1</li>
    <li class="li">Item 2</li>
    <li class="li">Item 3</li>
    <li class="li">Item 4</li>
    <li class="li">Item 5</li>
    <li class="li">Item 6</li>
    <li class="li">Item 7</li>
    <li class="li">Item 8</li>
    <li class="li">Item 9</li>
    <li class="li">Item 10</li>
  </ul>

  {% include '../../design/decorations/icon-hamburger/icon-hamburger.html.swig' %}
</nav>
