<section class="x-intrinsic-ratio-flexbox__iframe">
  <h3>Iframe</h3>

  <article class="article">
    <h3 class="article__title">{{ image.title }}</h3>

    <aside class="article__content">
      <h3 class="title">Some content here and an image</h3>

      <div class="intrinsic-ratio-flexbox-container">
        <iframe class="iframe" src="http://www.w3schools.com"></iframe>
      </div>
    </aside>

    <p>
      It's a footer !!!
    </p>
  </article>
</section>
